version: '3.4'

services:
    
    db:
      image: mysql
      container_name: db
      ports:
       - "3306:3306"
      environment:
        MYSQL_DATABASE: Django_Assignment
        MYSQL_USER: omar
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root

    backend:
      build: ./BackEnd/.
      container_name: backend
      command: "python manage.py runserver 0.0.0.0:8000 "
      ports:
       - 8000:8000
    
    frontend:
      build: ./FrontEnd/.
      container_name: frontend
      ports:
       - "4200:4200"
      depends_on:
      - backend
      
